# Default config is used even if no config file is specified in CLI. Undefined arguments will take the default values.
# default_config_file: /gpfsdswork/projects/idris/sos/ssos023/Projects/Plug-AI/Plug-AI/JZ_experiments/config_BrainTumour.yaml

# IDEA: MAKE DEFAULT CONFIG TRIGGER INDICATIONS PROGRESSIVELY ON HOW TO USE PLUG_AI (MISSING ARGUMENTS WHICH LEAD TO ERRORS?)

##################################################################################################
######################################## Data arguments : ########################################
##################################################################################################
# We must define precisely which arguments must be "mandatory" and are related to our general pipeline and which are related
# to the dataset class specificaly
dataset: nnU-Net
dataset_kwargs:
    nnunet_dataset_rootdir: "/gpfswork/rech/ibu/commun/nnUNet_experiment_kg/nnUNet_raw_data_base"
    task_id: 4
    #task_name: 'Hippocampus'
    raw_dataset_type: "MSD"
    raw_dataset_dir: "/gpfswork/rech/ibu/commun/datasets/MSD/Task04_Hippocampus"
    download_raw_dataset: False
    nbr_thread: 4
    progress: True

##################################################################################################
####################################### Model arguments : ########################################
##################################################################################################

model: nnU-Net     #model_type MODEL_TYPE
model_kwargs:     #model_args MODEL_ARGS
    nnunet_dataset_rootdir: "/gpfswork/rech/ibu/commun/nnUNet_experiment_kg/nnUNet_raw_data_base"
    nnunet_preprocessed_rootdir: "/gpfswork/rech/ibu/commun/nnUNet_experiment_kg/nnUNet_preprocessed"
    task_id: 4
    verify_dataset_integrity: False
    no_preprocessing: False
    planner_2d: "ExperimentPlanner2D_v21"
    planner_3d: "ExperimentPlanner3D_v21"
    nbr_thread: 8
    overwrite_plans: null
    overwrite_plans_identifier: null
    progress: True
model_weights_path: null

##################################################################################################
##################################### Execution arguments : ######################################
##################################################################################################
#Training settings
nb_epoch: 1
learning_rate: '5e-05' #lr, learning rate, either a value or a string in "list of strategies"
device: cuda
random_seed: 2022  # None for real randomness, set an integer for reproductibility
report_log: False

# You can choose between "Default", or a criterion in the list of valid optimizers.
# Complete optimizer_kwargs according to the args needed for the optimizer you selected
# "Default" option do not make use of any kwargs
loop: nnU-Net
loop_kwargs :
    nnunet_dataset_rootdir: "/gpfswork/rech/ibu/commun/nnUNet_experiment_kg/nnUNet_raw_data_base"
    nnunet_preprocessed_rootdir: "/gpfswork/rech/ibu/commun/nnUNet_experiment_kg/nnUNet_preprocessed"
    nnunet_experiment_dir: "/gpfswork/rech/ibu/commun/nnUNet_experiment_kg/nnUNet_preprocessed"
    network: "2d"
    network_trainer: "nnUNetTrainerV2"
    task: 4
    fold: "all"
    
lr_scheduler: None
lr_scheduler_kwargs:
#validation_only: 
#continue_training:
#plans_identifier:
#use_compressed_data:
#deterministic:
#npz:
#find_lr:
#valbest:
#fp32:
#val_folder:
#disable_saving:
#disable_postprocessing_on_folds: 
#val_disable_overwrite:
#disable_next_stage_pred:
#pretrained_weights:


# Execution settings

# Reporting settings



##################################################################################################
####################################### Global arguments : #######################################
##################################################################################################
config_file: null
export_config: null
mode: TRAINING # Choose between Training, Evaluation, Inference
verbose: FULL #Full, Restricted, None
seed: null

#Global arguments:
#config_file:
#config_file: ./config_Brats.yaml
##################################################################################################
######################################## Extra arguments : #######################################
##################################################################################################
