##################################################################################################
######################################## Data arguments : ########################################
##################################################################################################
dataset: nnU-Net
dataset_kwargs:
    nnunet_dataset_rootdir: "/gpfswork/rech/ibu/commun/nnUNet_experiment_kg/nnUNet_raw_data_base"
    task_id: 4
    raw_dataset_type: "MSD"
    raw_dataset_dir: "/gpfswork/rech/ibu/commun/datasets/MSD/Task04_Hippocampus"
    download_raw_dataset: False
    nbr_thread: 4
    progress: True

##################################################################################################
####################################### Model arguments : ########################################
##################################################################################################
model: nnU-Net     #model_type MODEL_TYPE
model_kwargs:     #model_args MODEL_ARGS

##################################################################################################
##################################### Execution arguments : ######################################
##################################################################################################
nb_epoch: 1
learning_rate: '5e-05' #lr, learning rate, either a value or a string in "list of strategies"
device: cuda
random_seed: 2022  # None for real randomness, set an integer for reproductibility
report_log: False
loop: nnU-Net
lr_scheduler: None
lr_scheduler_kwargs:

##################################################################################################
####################################### Global arguments : #######################################
##################################################################################################
config_file: null
export_config: null
mode: TRAINING # Choose between Training, Evaluation, Inference
verbose: FULL #Full, Restricted, None
seed: null
