# Default config is used even if no config file is specified in CLI. Undefined arguments will take the default values.
# default_config_file: /gpfsdswork/projects/idris/sos/ssos023/Projects/Plug-AI/Plug-AI/JZ_experiments/config_BrainTumour.yaml

# IDEA: MAKE DEFAULT CONFIG TRIGGER INDICATIONS PROGRESSIVELY ON HOW TO USE PLUG_AI (MISSING ARGUMENTS WHICH LEAD TO ERRORS?)

##################################################################################################
######################################## Data arguments : ########################################
##################################################################################################
# We must define precisely which arguments must be "mandatory" and are related to our general pipeline and which are related
# to the dataset class specificaly
dataset: BraTS # Maybe include it in dataset_kwargs.
dataset_kwargs:
  dataset_dir: /gpfswork/rech/ibu/commun/BraTS2021/BraTS2021_Training_Data/
  download_dataset: false
  dataset_param1: None
  categories:
  - cat0
  - cat1
  - cat2
  - cat3
  - cat4
  task: THIS IS A TEST
  transformation: BraTS_transform
preprocess: false
preprocess_kwargs:
#We will have to define the structure of the dataset according to each task and do some auto-selection of models accordingly
generate_signature: true
train_ratio: 0.8 # How to specify the split?
#val_ratio: 0.1
#test_ratio: 0.1
limit_sample: 20
batch_size: 2
shuffle: true
drop_last: true


##################################################################################################
####################################### Model arguments : ########################################
##################################################################################################

model: DynUnet
checkpoints_path: ./checkpoints
use_signature: false
res_out: false
# probably integrate res_out as a model_kwargs 
model_kwargs:
    #model_type MODEL_TYPE
    #model_args MODEL_ARGS

##################################################################################################
##################################### Execution arguments : ######################################
##################################################################################################
#Training settings
nb_epoch: 1
learning_rate: '5e-05' #lr, learning rate, either a value or a string in "list of strategies"
device: cuda
random_seed: 2022  # None for real randomness, set an integer for reproductibility
report_log: false

execution_kwargs:


# You can choose between "Default", or a criterion in the list of valid optimizers.
# Complete optimizer_kwargs according to the args needed for the optimizer you selected
# "Default" option do not make use of any kwargs
loop: Default
loop_kwargs:
  step: Default
optimizer: SGD
optimizer_kwargs:
  lr: 0.0001
  momentum: 0.99
  weight_decay: 3e-05
  nesterov: true
criterion: DiceCELoss
criterion_kwargs:
  to_onehot_y: true
  softmax: true
config_file:
export_config: /gpfsdswork/projects/rech/ibu/ssos023/Plug-AI/JZ_experiments/config_saved_test.yaml
mode: TRAINING # Choose between Training, Evaluation, Inference
verbose: RESTRICTED #Full, Restricted, None
seed:

#Global arguments:
#config_file:
#config_file: ./config_Brats.yaml
##################################################################################################
######################################## Extra arguments : #######################################
##################################################################################################
